import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { GoogleAnalytics } from "@next/third-parties/google";


const inter = Geist({ subsets: ["latin"] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  /* SEO */
  generator: "Next.js",
  applicationName: "Kayc Farias Portfolio site",
  keywords: ["Portifolio","Next.js", "React", "JavaScript", "TypeScript", "TailwindCSS", ],
  creator: "Kayc Farias",
  title: "Kayc Farias",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} scroll-smooth`}
      suppressHydrationWarning
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased light-background dark:dark-background`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
      {/* Google Analytics */}
      <GoogleAnalytics gaId="G-THFTGJ6T8F" />
    </html>
  );
}
